"""add chart unique constraint

Revision ID: 9941e98f8708
Revises: 9fbfddb3b5ad
Create Date: 2026-06-13 20:20:40.732356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9941e98f8708'
down_revision: Union[str, Sequence[str], None] = '9fbfddb3b5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_profile_chart_system', 'chart_calculations', ['profile_id', 'chart_system'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_profile_chart_system', 'chart_calculations', type_='unique')
    # ### end Alembic commands ###
