"""add chart version

Revision ID: 9fbfddb3b5ad
Revises: c156b0e96811
Create Date: 2026-06-13 20:01:18.396286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbfddb3b5ad'
down_revision: Union[str, Sequence[str], None] = 'c156b0e96811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
    'chart_calculations',
    sa.Column(
        'version',
        sa.Integer(),
        nullable=False,
        server_default='1'
    )
)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chart_calculations', 'version')
    # ### end Alembic commands ###
