"""add unique constraint to birth_profiles user_id

Revision ID: c156b0e96811
Revises: 1b04763d81f3
Create Date: 2026-06-12 22:38:10.684422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c156b0e96811'
down_revision: Union[str, Sequence[str], None] = '1b04763d81f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'birth_profiles', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'birth_profiles', type_='unique')
    # ### end Alembic commands ###
